[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
verbosity = 2
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200

# Profile for FFI-dependent tests - inherits everything from default
[profile.ffi-tests]
ffi = true
fs_permissions = [{ access = "read-write", path = "./swapdatas-cache/" }]

[rpc_endpoints]
base = "${BASE_URL}"
optimism = "${OPTIMISM_URL}"
arbitrum = "${ARBITRUM_URL}"
polygon = "${POLYGON_URL}"
ethereum = "${ETHEREUM_URL}"
